export type InteractionSurface =
  | 'studio'
  | 'auth'
  | 'profile'
  | 'pricing'
  | 'stems'
  | 'licenses'
  | 'onboarding'

export type InteractionMultiplicity = 'one' | 'repeated'

export interface InteractionAccessibilityExemption {
  reason: string
  alternativeInteractionIds: readonly string[]
}

export interface InteractionManifestEntry {
  id: string
  surface: InteractionSurface
  expectedRole: string
  expectedName: string
  outcome: string
  multiplicity: InteractionMultiplicity
  behaviorSpec: string
  relatedE2e?: string
  notes?: string
  accessibilityExemption?: InteractionAccessibilityExemption
}

type EntryFields = [
  id: string,
  surface: InteractionSurface,
  expectedRole: string,
  expectedName: string,
  outcome: string,
  multiplicity?: InteractionMultiplicity,
  notes?: string,
  accessibilityExemption?: InteractionAccessibilityExemption,
]

function traced(behaviorSpec: string, relatedE2e?: string) {
  return (...fields: EntryFields): InteractionManifestEntry => {
    const [
      id,
      surface,
      expectedRole,
      expectedName,
      outcome,
      multiplicity = 'one',
      notes,
      accessibilityExemption,
    ] = fields
    return {
      id,
      surface,
      expectedRole,
      expectedName,
      outcome,
      multiplicity,
      behaviorSpec,
      ...(relatedE2e ? { relatedE2e } : {}),
      ...(notes ? { notes } : {}),
      ...(accessibilityExemption ? { accessibilityExemption } : {}),
    }
  }
}

const app = traced('src/App.test.tsx', 'e2e/smoke.spec.ts')
const licenses = traced(
  'src/acknowledgements/AcknowledgementsPage.test.tsx',
  'e2e/acknowledgements.spec.ts',
)
const auth = traced('src/auth/AuthBar.test.tsx', 'e2e/auth.spec.ts')
const authDialog = traced('src/auth/AuthDialog.test.tsx', 'e2e/auth.spec.ts')
const authCallback = traced('src/app/AuthCallbackEffect.test.tsx', 'e2e/auth.spec.ts')
const profile = traced('src/auth/ProfilePage.test.tsx', 'e2e/auth.spec.ts')
const pricing = traced('src/billing/PricingPage.test.tsx', 'e2e/pricing.spec.ts')
const aiStudio = traced('src/composer/components/AiStudioPanel.test.tsx', 'e2e/assistant.spec.ts')
const aiInspector = traced('src/composer/components/AiInspector.test.tsx', 'e2e/assistant.spec.ts')
const assistant = traced(
  'src/composer/components/AssistantPanel.test.tsx',
  'e2e/assistant.spec.ts',
)
const automation = traced(
  'src/composer/components/AutomationLane.test.tsx',
  'e2e/automation.spec.ts',
)
const instrumentBrowser = traced('src/composer/components/InstrumentBrowser.test.tsx')
const midi = traced('src/composer/components/MidiControls.test.tsx', 'e2e/midi.spec.ts')
const mixer = traced('src/composer/components/MixerPanel.test.tsx', 'e2e/automation.spec.ts')
const piano = traced('src/composer/components/PianoRoll.test.tsx', 'e2e/pro-editing.spec.ts')
const plugins = traced('src/composer/components/PluginsPanel.test.tsx', 'e2e/plugins.spec.ts')
const pluginTools = traced('src/composer/components/PluginToolHost.test.tsx', 'e2e/plugins.spec.ts')
const project = traced('src/composer/components/ProjectToolbar.test.tsx', 'e2e/composer.spec.ts')
const quickStart = traced(
  'src/composer/components/QuickStartGallery.test.tsx',
  'e2e/start-center.spec.ts',
)
const startCenter = traced(
  'src/composer/components/StartCenter.test.tsx',
  'e2e/start-center.spec.ts',
)
const projectFlow = traced('src/composer/Composer.test.tsx', 'e2e/start-center.spec.ts')
const share = traced(
  'src/composer/components/ShareProjectButton.test.tsx',
  'e2e/collaboration.spec.ts',
)
const trackInspector = traced(
  'src/composer/components/TrackInspector.test.tsx',
  'e2e/multitrack.spec.ts',
)
const trackRail = traced('src/composer/components/TrackRail.test.tsx', 'e2e/multitrack.spec.ts')
const detailLane = traced('src/composer/components/EditorDetailLane.test.tsx', 'e2e/pro-editing.spec.ts')
const shortcuts = traced(
  'src/composer/components/ShortcutHelpDialog.test.tsx',
  'e2e/interaction-contract.spec.ts',
)
const transport = traced('src/composer/components/TransportBar.test.tsx', 'e2e/audio.spec.ts')
const composer = traced('src/composer/Composer.test.tsx', 'e2e/composer.spec.ts')
const studioFrame = traced('src/studio/StudioFrame.test.tsx', 'e2e/studio-frame.spec.ts')
const studioInspector = traced(
  'src/studio/StudioInspectorPanels.test.tsx',
  'e2e/studio-frame.spec.ts',
)
const studioHelp = traced('src/studio/StudioHelpMenu.test.tsx', 'e2e/studio-frame.spec.ts')
const mobile = traced(
  'src/mobile/mobileComponents.test.tsx',
  'e2e/mobile-contract.spec.ts',
)
const examplePlugin = traced(
  'src/composer/plugins/examples/helloPlugin.test.tsx',
  'e2e/plugins.spec.ts',
)
const onboarding = traced(
  'src/onboarding/OnboardingTour.test.tsx',
  'e2e/onboarding.spec.ts',
)
const stems = traced('src/stems/StemsPage.test.tsx', 'e2e/stems.spec.ts')

export const interactionManifest: readonly InteractionManifestEntry[] = [
  app(
    'app.skip-to-composer',
    'studio',
    'link',
    'Skip to editor',
    'Moves keyboard focus to the composer main region.',
  ),
  app(
    'app.nav.stems',
    'studio',
    'button',
    '/Stems|Back to composer/',
    'Shows the stems surface or returns to the composer.',
  ),
  app(
    'app.nav.pricing',
    'studio',
    'button',
    '/Pricing|Back to composer/',
    'Shows the pricing surface or returns to the composer.',
  ),
  app(
    'app.nav.licenses',
    'studio',
    'button',
    '/Third-party licenses|Back to composer/',
    'Shows the licenses and acknowledgements surface or returns to the composer.',
  ),
  app(
    'app.theme.open',
    'studio',
    'button',
    'Choose theme',
    'Opens the theme menu and exposes system, light, and dark choices.',
  ),
  app(
    'app.theme.select',
    'studio',
    'menuitemradio',
    '/System theme|Light theme|Dark theme/',
    'Persists the selected theme preference and applies it to the document.',
    'repeated',
  ),
  app(
    'app.not-found.studio',
    'studio',
    'button',
    'Return to Studio',
    'Returns an unknown browser-history route to the Studio route.',
  ),

  licenses(
    'licenses.external-link',
    'licenses',
    'link',
    '/.+/',
    'Navigates to the selected license, notice, package, or project resource in a new tab.',
    'repeated',
    'Native external links preserve their current targets and rel attributes.',
  ),
  licenses(
    'licenses.close',
    'licenses',
    'button',
    'Back to composer',
    'Returns from licenses and acknowledgements to the composer.',
  ),
  auth(
    'auth.profile.open',
    'auth',
    'button',
    'Profile',
    'Opens the authenticated profile editor and updates the pressed state.',
  ),
  auth(
    'auth.sign-out',
    'auth',
    'button',
    '/Sign out|Signing out/',
    'Waits for the local project-store transition, then signs out and applies route navigation.',
  ),
  auth(
    'auth.panel.toggle',
    'auth',
    'button',
    'Sign in',
    'Opens the shared sign-in Dialog.',
  ),
  authDialog(
    'auth.dialog.close',
    'auth',
    'button',
    'Close',
    'Closes the sign-in Dialog and restores focus to its launcher.',
  ),
  authDialog(
    'auth.registration.display-name',
    'auth',
    'textbox',
    'Display name',
    'Updates the pending registration display name.',
  ),
  authDialog(
    'auth.credentials.email',
    'auth',
    'textbox',
    'Email',
    'Updates the credentials email and clears stale registration success.',
  ),
  authDialog(
    'auth.credentials.password',
    'auth',
    'input',
    'Password',
    'Updates the credentials password submitted for sign-in or registration.',
  ),
  authDialog(
    'auth.credentials.submit',
    'auth',
    'button',
    '/Sign in|Signing in\\.\\.\\.|Create account/',
    'Submits credentials and exposes authenticated, success, or error state.',
  ),
  authDialog(
    'auth.mode.toggle',
    'auth',
    'button',
    '/Create an account|Already have an account/',
    'Switches between sign-in and registration fields and copy.',
  ),
  authDialog(
    'auth.magic-link.email',
    'auth',
    'textbox',
    'Or get a magic sign-in link',
    'Updates the passwordless sign-in email and clears stale success.',
  ),
  authDialog(
    'auth.magic-link.submit',
    'auth',
    'button',
    'Email me a link',
    'Requests a magic link and exposes success or error state.',
  ),
  authDialog(
    'auth.provider.sign-in',
    'auth',
    'link',
    '/.+/',
    'Navigates to the selected external authentication provider.',
    'repeated',
    'Native link behavior.',
  ),
  authCallback(
    'auth.callback.dismiss',
    'auth',
    'button',
    'Dismiss authentication status',
    'Dismisses the one-shot authentication callback status.',
  ),

  profile(
    'profile.close',
    'profile',
    'button',
    'Back to composer',
    'Returns from the profile editor to the composer.',
  ),
  profile(
    'profile.retry',
    'profile',
    'button',
    'Retry',
    'Retries a failed profile load without leaving the guarded route.',
  ),
  profile(
    'profile.display-name',
    'profile',
    'textbox',
    'Display name',
    'Updates the draft display name and clears the saved indicator.',
  ),
  profile(
    'profile.bio',
    'profile',
    'textbox',
    'Bio',
    'Updates the draft biography and clears the saved indicator.',
  ),
  profile(
    'profile.avatar-url',
    'profile',
    'textbox',
    'Avatar URL',
    'Updates the draft avatar URL and clears the saved indicator.',
  ),
  profile(
    'profile.save',
    'profile',
    'button',
    'Save changes',
    'Persists profile fields and exposes saved or error state.',
  ),

  pricing(
    'pricing.close',
    'pricing',
    'button',
    'Back to composer',
    'Returns from pricing to the composer.',
  ),
  pricing(
    'pricing.retry',
    'pricing',
    'button',
    'Retry',
    'Retries loading the current server-authoritative plan.',
  ),
  pricing(
    'pricing.upgrade',
    'pricing',
    'button',
    'Upgrade to Pro',
    'Starts checkout and navigates to the returned checkout URL or exposes an error.',
  ),
  pricing(
    'pricing.manage',
    'pricing',
    'button',
    'Manage billing',
    'Opens the billing portal URL or exposes an error.',
  ),

  aiInspector(
    'studio.ai.inspector.tab',
    'studio',
    'tab',
    '/Basic|Advanced/',
    'Switches between the Basic Assistant and Advanced AI presentation without changing controllers.',
    'repeated',
  ),
  aiStudio(
    'studio.ai.upgrade',
    'studio',
    'link',
    'View plans',
    'Routes a locked Advanced AI action to pricing without invoking its controller.',
  ),
  aiStudio(
    'studio.ai.feature.select',
    'studio',
    'radio',
    '/Text to motif|Style transfer|Groove|Auto-master/',
    'Selects an AI Studio feature and displays its controls.',
    'repeated',
  ),
  aiStudio(
    'studio.ai.motif.prompt',
    'studio',
    'textbox',
    'Prompt',
    'Updates the text-to-motif prompt.',
  ),
  aiStudio(
    'studio.ai.motif.length',
    'studio',
    'slider',
    '/Motif length/',
    'Updates motif length and its beat readout.',
  ),
  aiStudio(
    'studio.ai.motif.create',
    'studio',
    'button',
    'Create motif',
    'Creates motif notes on the selected track or exposes validation state.',
  ),
  aiStudio(
    'studio.ai.style.select',
    'studio',
    'combobox',
    '/Style/',
    'Updates the selected style-transfer preset.',
  ),
  aiStudio(
    'studio.ai.style.apply',
    'studio',
    'button',
    'Apply style',
    'Applies the selected style to the current track or remains disabled when locked.',
  ),
  aiStudio(
    'studio.ai.groove.select',
    'studio',
    'combobox',
    '/Groove/',
    'Updates the selected groove preset.',
  ),
  aiStudio(
    'studio.ai.groove.intensity',
    'studio',
    'slider',
    '/Intensity/',
    'Updates groove intensity and its percentage readout.',
  ),
  aiStudio(
    'studio.ai.groove.apply',
    'studio',
    'button',
    'Apply groove',
    'Applies the selected groove and intensity to the current track.',
  ),
  aiStudio(
    'studio.ai.mastering.analyze',
    'studio',
    'button',
    'Analyze mix',
    'Analyzes the mix and renders the mastering report or locked state.',
  ),

  assistant(
    'studio.assistant.action.select',
    'studio',
    'radio',
    '/Continue|Generate|Harmonize/',
    'Selects the assistant action and updates parameter availability.',
    'repeated',
  ),
  assistant(
    'studio.assistant.temperature',
    'studio',
    'slider',
    '/Temperature/',
    'Updates generation temperature and its readout.',
  ),
  assistant(
    'studio.assistant.length',
    'studio',
    'slider',
    '/Length/',
    'Updates generation length and its beat readout.',
  ),
  assistant(
    'studio.assistant.generate',
    'studio',
    'button',
    '/Generate|Cancel/',
    'Starts generation or cancels the active request and updates status.',
  ),
  assistant(
    'studio.assistant.preview',
    'studio',
    'button',
    'Preview',
    'Auditions the generated suggestion.',
  ),
  assistant(
    'studio.assistant.accept',
    'studio',
    'button',
    'Accept',
    'Commits the generated suggestion to the selected track.',
  ),
  assistant(
    'studio.assistant.discard',
    'studio',
    'button',
    'Discard',
    'Removes the generated suggestion from the panel.',
  ),

  automation(
    'studio.automation.add-point',
    'studio',
    'button',
    'Add point',
    'Writes the current automation value at the playhead.',
    'repeated',
  ),
  automation(
    'studio.automation.clear',
    'studio',
    'button',
    '/Clear .+ automation/',
    'Removes every point from the selected automation lane.',
    'repeated',
  ),
  automation(
    'studio.automation.lane',
    'studio',
    'presentation',
    '',
    'Writes an automation point at the pointer-derived beat and value.',
    'repeated',
    'Known pointer-only baseline gap.',
    {
      reason:
        'The SVG intentionally remains role=presentation with no accessible name in the current UX.',
      alternativeInteractionIds: ['studio.automation.add-point'],
    },
  ),
  automation(
    'studio.automation.remove-point',
    'studio',
    'button',
    '/Remove .+ point at beat/',
    'Removes the selected automation point.',
    'repeated',
  ),

  trackInspector(
    'studio.track.instrument',
    'studio',
    'button',
    '/Choose instrument for .+/',
    'Opens live instrument discovery for the repeated track.',
  ),
  instrumentBrowser(
    'studio.instrument-browser.close',
    'studio',
    'button',
    'Close',
    'Closes instrument discovery and returns focus to its trigger.',
  ),
  instrumentBrowser(
    'studio.instrument-browser.search',
    'studio',
    'combobox',
    'Search instruments',
    'Filters active registry instruments by normalized metadata.',
  ),
  instrumentBrowser(
    'studio.instrument-browser.kind',
    'studio',
    'button',
    '/All|Melodic|Drums/',
    'Filters discovery by melodic or drum kind and updates aria-pressed.',
    'repeated',
  ),
  instrumentBrowser(
    'studio.instrument-browser.group',
    'studio',
    'combobox',
    'Group',
    'Filters discovery by live registry group.',
  ),
  instrumentBrowser(
    'studio.instrument-browser.option',
    'studio',
    'option',
    '/.+/',
    'Assigns the selected live registry instrument to the active track.',
    'repeated',
  ),
  instrumentBrowser(
    'studio.instrument-browser.list',
    'studio',
    'listbox',
    'Available instruments',
    'Exposes the filtered live-registry options for keyboard and assistive technology.',
  ),
  midi(
    'studio.midi.settings',
    'studio',
    'button',
    'MIDI',
    'Opens device selection and recording quantize settings.',
  ),
  midi(
    'studio.midi.device',
    'studio',
    'combobox',
    'MIDI device',
    'Selects the active native MIDI input device.',
  ),
  midi(
    'studio.midi.arm',
    'studio',
    'button',
    'Record',
    'Arms or disarms MIDI recording and updates aria-pressed.',
  ),
  midi(
    'studio.midi.quantize',
    'studio',
    'checkbox',
    'Quantize while recording',
    'Enables or disables quantization for recorded MIDI notes.',
  ),

  mixer(
    'studio.mixer.track.gain',
    'studio',
    'slider',
    '/Gain/',
    'Updates track gain and its decibel readout.',
    'repeated',
  ),
  mixer(
    'studio.mixer.track.pan',
    'studio',
    'slider',
    '/Pan/',
    'Updates track pan and its left, center, or right readout.',
    'repeated',
  ),
  mixer(
    'studio.mixer.track.mute',
    'studio',
    'button',
    'Mute',
    'Mutes or unmutes the track and updates aria-pressed.',
    'repeated',
  ),
  mixer(
    'studio.mixer.track.solo',
    'studio',
    'button',
    'Solo',
    'Solos or unsolos the track and updates aria-pressed.',
    'repeated',
  ),
  mixer(
    'studio.mixer.insert.toggle',
    'studio',
    'checkbox',
    '/.+/',
    'Enables or disables the selected insert effect.',
    'repeated',
  ),
  mixer(
    'studio.mixer.insert.remove',
    'studio',
    'button',
    '/Remove .+ from .+/',
    'Removes the selected insert effect from its track.',
    'repeated',
  ),
  mixer(
    'studio.mixer.insert.select',
    'studio',
    'combobox',
    '/Add insert to .+/',
    'Selects the insert effect to add to a track.',
    'repeated',
  ),
  mixer(
    'studio.mixer.insert.add',
    'studio',
    'button',
    'Add',
    'Adds the selected insert effect to a track.',
    'repeated',
  ),
  mixer(
    'studio.mixer.insert.parameter',
    'studio',
    'slider',
    '/.+/',
    'Edits a registered insert-effect parameter and commits one undoable gesture.',
    'repeated',
  ),
  mixer(
    'studio.mixer.master.gain',
    'studio',
    'slider',
    '/Gain/',
    'Updates master gain and its decibel readout.',
  ),
  mixer(
    'studio.mixer.master.limiter',
    'studio',
    'checkbox',
    'Limiter',
    'Enables or disables the master limiter.',
  ),
  mixer(
    'studio.mixer.master.ceiling',
    'studio',
    'slider',
    '/Ceiling/',
    'Updates the limiter ceiling and its decibel readout.',
  ),

  piano(
    'studio.piano-roll.zoom.time-out',
    'studio',
    'button',
    'Zoom out horizontally (time)',
    'Decreases horizontal piano-roll zoom and updates the zoom readout.',
  ),
  piano(
    'studio.piano-roll.zoom.time-in',
    'studio',
    'button',
    'Zoom in horizontally (time)',
    'Increases horizontal piano-roll zoom and updates the zoom readout.',
  ),
  piano(
    'studio.piano-roll.zoom.pitch-out',
    'studio',
    'button',
    'Zoom out vertically (pitch)',
    'Decreases vertical piano-roll zoom and updates the zoom readout.',
  ),
  piano(
    'studio.piano-roll.zoom.pitch-in',
    'studio',
    'button',
    'Zoom in vertically (pitch)',
    'Increases vertical piano-roll zoom and updates the zoom readout.',
  ),
  piano(
    'studio.piano-roll.zoom.reset',
    'studio',
    'button',
    'Reset zoom',
    'Restores default horizontal and vertical piano-roll zoom.',
  ),
  piano(
    'studio.piano-roll.quantize.strength',
    'studio',
    'slider',
    'Quantize strength',
    'Updates quantize strength and its percentage readout.',
  ),
  piano(
    'studio.piano-roll.quantize.apply',
    'studio',
    'button',
    '/Quantize .+ to the current snap grid/',
    'Quantizes selected or all notes and updates note positions.',
  ),
  piano(
    'studio.piano-roll.velocity.toggle',
    'studio',
    'button',
    'Toggle velocity lane',
    'Shows or hides the velocity lane and updates aria-pressed.',
  ),
  piano(
    'studio.piano-roll.grid',
    'studio',
    'application',
    '/Note grid/',
    'Adds notes by pointer or keyboard and supports caret, selection, movement, resizing, and deletion.',
    'one',
    'Custom keyboard and pointer surface.',
  ),
  piano(
    'studio.piano-roll.note',
    'studio',
    'button',
    '/[A-G][#b]?\\d at beat/',
    'Selects or drags a note and updates its pressed state and position.',
    'repeated',
    'Pointer drag and native button keyboard activation.',
  ),
  piano(
    'studio.piano-roll.note.resize-start',
    'studio',
    'none',
    '',
    'Resizes the note from its start edge.',
    'repeated',
    'Aria-hidden pointer handle.',
    {
      reason: 'The resize handle is aria-hidden and the containing note button owns keyboard access.',
      alternativeInteractionIds: ['studio.piano-roll.note'],
    },
  ),
  piano(
    'studio.piano-roll.note.resize-end',
    'studio',
    'none',
    '',
    'Resizes the note from its end edge.',
    'repeated',
    'Aria-hidden pointer handle.',
    {
      reason: 'The resize handle is aria-hidden and the containing note button owns keyboard access.',
      alternativeInteractionIds: ['studio.piano-roll.note'],
    },
  ),
  piano(
    'studio.piano-roll.velocity.note',
    'studio',
    'button',
    '/Velocity for .+ at beat/',
    'Adjusts one note velocity by pointer drag or keyboard.',
    'repeated',
  ),
  piano(
    'studio.piano-roll.velocity.selected',
    'studio',
    'slider',
    '/Velocity/',
    'Updates the selected note velocity and numeric readout.',
  ),

  pluginTools(
    'studio.plugins.panel.open',
    'studio',
    'tab',
    '/.+/',
    'Mounts the selected visible extension tool and unmounts inactive tools.',
    'repeated',
  ),
  plugins(
    'studio.plugins.keybinding.record',
    'studio',
    'button',
    '/Shortcut for command/',
    'Enters keybinding capture, persists the next shortcut, or clears it with Escape.',
    'repeated',
    'Custom keyboard capture surface.',
  ),
  plugins(
    'studio.plugins.plugin.toggle',
    'studio',
    'checkbox',
    '/.+/',
    'Enables or disables a non-built-in plugin.',
    'repeated',
  ),
  plugins(
    'studio.plugins.command.run',
    'studio',
    'button',
    '/.+/',
    'Runs the selected contributed plugin command.',
    'repeated',
  ),
  plugins(
    'studio.plugins.panel.toggle',
    'studio',
    'checkbox',
    '/.+/',
    'Shows or hides the selected contributed plugin panel.',
    'repeated',
  ),

  project(
    'studio.project.name',
    'studio',
    'textbox',
    'Project name',
    'Renames the current project and updates project state.',
  ),
  project(
    'studio.project.menu.toggle',
    'studio',
    'button',
    'Project',
    'Opens the grouped New, Open, and import commands.',
  ),
  project(
    'studio.project.new',
    'studio',
    'menuitem',
    'New project',
    'Opens the project browser without replacing the current document.',
  ),
  startCenter(
    'studio.project.demo',
    'studio',
    'button',
    '/Demo pattern/',
    'Safely flushes the current document and loads the bundled demo as a fresh project.',
  ),
  project(
    'studio.project.save',
    'studio',
    'button',
    'Save',
    'Persists the project and exposes save status.',
  ),
  project(
    'studio.project.open',
    'studio',
    'menuitem',
    'Open project',
    'Opens the project browser at the recent-project flow.',
  ),
  project(
    'studio.project.import.trigger',
    'studio',
    'menuitem',
    'Import file',
    'Opens the hidden project, MusicXML, or plugin-format file chooser.',
    'one',
    'Trigger for studio.project.import.file.',
  ),
  project(
    'studio.project.import.file',
    'studio',
    'button',
    'Import project or MusicXML file',
    'Reads the selected file and imports a project, MusicXML, or plugin package.',
    'one',
    'Visually hidden native file input.',
  ),
  project(
    'studio.project.export',
    'studio',
    'button',
    'Export & share',
    'Opens the grouped export and portable-sharing commands.',
  ),
  project(
    'studio.project.export.format',
    'studio',
    'menuitem',
    '/Export .+/',
    'Downloads the current project in the selected built-in or plugin-contributed format.',
    'repeated',
  ),
  project(
    'studio.project.share',
    'studio',
    'menuitem',
    'Share snapshot',
    'Copies a share payload or downloads a fallback snapshot and exposes status.',
  ),
  project(
    'studio.project.midi-import.trigger',
    'studio',
    'menuitem',
    'Import MIDI',
    'Opens the hidden MIDI file chooser.',
    'one',
    'Trigger for studio.project.midi-import.file.',
  ),
  project(
    'studio.project.midi-import.file',
    'studio',
    'button',
    'Import MIDI file',
    'Reads the selected MIDI file into the current project.',
    'one',
    'Visually hidden native file input.',
  ),
  project(
    'studio.project.midi-export',
    'studio',
    'menuitem',
    'Export MIDI',
    'Downloads the current project as a MIDI file.',
  ),

  project(
    'studio.save.retry',
    'studio',
    'button',
    'Retry save',
    'Retries persistence for the latest dirty revision after an autosave error.',
  ),

  startCenter(
    'start-center.blank',
    'studio',
    'button',
    '/Blank project/',
    'Creates a fresh blank project through the safe replacement coordinator.',
  ),
  startCenter(
    'start-center.import.trigger',
    'studio',
    'button',
    '/Import project/',
    'Opens the Start Center project, MusicXML, or plugin-format chooser.',
  ),
  startCenter(
    'start-center.import.file',
    'studio',
    'button',
    'Import project or MusicXML from Start Center',
    'Reads and safely imports the selected project, MusicXML, or plugin-format file.',
  ),
  startCenter(
    'start-center.midi-import.trigger',
    'studio',
    'button',
    '/Import MIDI/',
    'Opens the Start Center MIDI chooser.',
  ),
  startCenter(
    'start-center.midi-import.file',
    'studio',
    'button',
    'Import MIDI from Start Center',
    'Reads and safely imports the selected MIDI file.',
  ),
  startCenter(
    'start-center.recent.open',
    'studio',
    'button',
    '/.+/',
    'Flushes pending edits and opens the selected recent project.',
    'repeated',
  ),
  startCenter(
    'start-center.recents.retry',
    'studio',
    'button',
    'Retry',
    'Retries loading recent projects from the active local or remote store.',
  ),
  startCenter(
    'start-center.restore.retry',
    'studio',
    'button',
    'Retry restore',
    'Retries shared, recovery, and last-project hydration precedence.',
  ),
  startCenter(
    'start-center.restore.continue',
    'studio',
    'button',
    'Continue to Start Center',
    'Continues for this mount without deleting or overwriting saved project pointers.',
  ),
  projectFlow(
    'studio.project-browser.close',
    'studio',
    'button',
    'Close project browser',
    'Closes the in-Studio project browser and returns focus to its trigger.',
  ),
  projectFlow(
    'studio.project-replacement.retry',
    'studio',
    'button',
    'Retry save',
    'Retries the blocked flush and replaces the project only after success.',
  ),
  projectFlow(
    'studio.project-replacement.cancel',
    'studio',
    'button',
    'Keep editing',
    'Cancels the pending replacement and preserves the current project.',
  ),
  projectFlow(
    'studio.project-replacement.discard',
    'studio',
    'button',
    'Discard changes and continue',
    'Explicitly discards the failed pending revision and completes the requested replacement.',
  ),

  quickStart(
    'studio.quick-start.load',
    'studio',
    'button',
    '/.+/',
    'Loads the selected quick-start template as the current project.',
    'repeated',
  ),
  share(
    'studio.share.toggle',
    'studio',
    'button',
    'Share',
    'Expands or collapses share-link controls and loads existing links.',
  ),
  share(
    'studio.share.create-editor',
    'studio',
    'button',
    'Create editor link',
    'Creates, displays, and copies a new editor link.',
  ),
  share(
    'studio.share.create-viewer',
    'studio',
    'button',
    'Create viewer link',
    'Creates, displays, and copies a new viewer link.',
  ),
  share(
    'studio.share.copy',
    'studio',
    'button',
    '/Copy link|Copied/',
    'Copies the repeated share link and changes its button text to Copied.',
    'repeated',
  ),
  share(
    'studio.share.revoke',
    'studio',
    'button',
    'Revoke',
    'Revokes and removes the repeated share link.',
    'repeated',
  ),

  trackRail(
    'studio.track.visibility-all',
    'studio',
    'button',
    '/Show all tracks|Show only selected/',
    'Shows all tracks or only the selected track on the piano roll.',
  ),
  composer(
    'studio.history.undo',
    'studio',
    'button',
    'Undo',
    'Reverts the latest local document edit without affecting selection or remote edits.',
  ),
  composer(
    'studio.history.redo',
    'studio',
    'button',
    'Redo',
    'Reapplies the latest locally undone document edit.',
  ),
  composer(
    'studio.shortcuts.open',
    'studio',
    'button',
    'Shortcuts',
    'Opens grouped and searchable keyboard shortcut help.',
  ),
  trackRail(
    'studio.track.delete.dialog',
    'studio',
    'alertdialog',
    '/Delete .+/',
    'Owns focus while confirming destructive removal of a populated track.',
  ),
  trackRail(
    'studio.track.delete.confirm',
    'studio',
    'button',
    'Delete track',
    'Confirms removal of a populated track and its notes, automation, and mix state.',
  ),
  trackRail(
    'studio.track.delete.cancel',
    'studio',
    'button',
    'Cancel',
    'Cancels destructive track removal.',
  ),
  detailLane(
    'studio.editor-detail.tab',
    'studio',
    'tab',
    '/Velocity|Automation|Properties/',
    'Selects the contextual editor detail lane.',
    'repeated',
  ),
  shortcuts(
    'studio.shortcuts.dialog',
    'studio',
    'dialog',
    'Keyboard shortcuts',
    'Owns focus and suppresses Studio-global commands while shortcut help is open.',
  ),
  shortcuts(
    'studio.shortcuts.close',
    'studio',
    'button',
    'Close',
    'Closes the keyboard shortcuts dialog.',
  ),
  shortcuts(
    'studio.shortcuts.search',
    'studio',
    'textbox',
    'Search commands',
    'Filters core and extension commands in keyboard shortcut help.',
  ),
  trackRail('studio.track.add', 'studio', 'button', '/Add track/', 'Adds and selects a new track.'),
  composer(
    'studio.track.solo',
    'studio',
    'button',
    '/Solo|Unsolo/',
    'Toggles the persisted solo state for a repeated track from the compact rail.',
    'repeated',
  ),
  trackRail(
    'studio.track.select',
    'studio',
    'button',
    '/Select|Selected/',
    'Selects the repeated track for editing and updates aria-pressed.',
    'repeated',
  ),
  trackInspector(
    'studio.track.name',
    'studio',
    'textbox',
    'Track name',
    'Renames the repeated track.',
  ),
  trackRail(
    'studio.track.visibility',
    'studio',
    'button',
    '/Show|Hide|is shown/',
    'Shows or hides the repeated non-selected track on the piano roll.',
    'repeated',
  ),
  trackRail(
    'studio.track.mute',
    'studio',
    'button',
    '/Mute|Muted/',
    'Mutes or unmutes the repeated track and updates aria-pressed.',
    'repeated',
  ),
  trackRail(
    'studio.track.delete',
    'studio',
    'button',
    '/Delete .+/',
    'Deletes the repeated track unless it is the only track.',
    'repeated',
  ),

  transport(
    'studio.transport.play',
    'studio',
    'button',
    '/Play|Pause/',
    'Starts or pauses playback and updates aria-pressed.',
  ),
  transport(
    'studio.transport.stop',
    'studio',
    'button',
    '/Stop/',
    'Stops playback and resets position.',
  ),
  transport(
    'studio.transport.tempo',
    'studio',
    'spinbutton',
    'Tempo',
    'Updates project tempo within the native numeric range.',
  ),
  transport(
    'studio.transport.loop',
    'studio',
    'button',
    '/Loop/',
    'Enables or disables loop playback and updates aria-pressed.',
  ),
  transport(
    'studio.transport.snap',
    'studio',
    'combobox',
    'Snap',
    'Updates the editor snap interval.',
  ),

  composer(
    'studio.empty.load-demo',
    'studio',
    'button',
    'Load a demo pattern',
    'Loads the demo pattern from the empty composer state.',
  ),
  studioFrame(
    'studio.view.write',
    'studio',
    'button',
    'Write',
    'Switches the primary workspace to the persistent writing surface.',
  ),
  studioFrame(
    'studio.view.mix',
    'studio',
    'button',
    'Mix',
    'Switches the primary workspace to the mixer without resetting transport state.',
  ),
  studioFrame(
    'studio.rail.toggle',
    'studio',
    'button',
    'Tracks',
    'Collapses or restores the persistent track rail and reallocates editor space.',
  ),
  studioFrame(
    'studio.inspector.toggle',
    'studio',
    'button',
    'Inspector',
    'Mounts or removes the contextual inspector and updates aria-expanded.',
  ),
  studioInspector(
    'studio.inspector.panel',
    'studio',
    'tab',
    '/Track|AI|Extensions/',
    'Switches the inspector to one mounted contextual panel.',
    'repeated',
  ),
  studioHelp(
    'studio.help.toggle',
    'studio',
    'button',
    'Help',
    'Opens the Studio help menu and exposes secondary routed destinations.',
  ),
  mobile(
    'mobile.task.open',
    'studio',
    'button',
    '/Project:|Tracks:|Notes:|Tools:/',
    'Opens the selected full-screen mobile composer task.',
    'repeated',
  ),
  mobile(
    'mobile.help.open',
    'studio',
    'button',
    'Help and keyboard shortcuts',
    'Opens touch guidance and attached keyboard shortcuts.',
  ),
  mobile(
    'mobile.notes.mode',
    'studio',
    'button',
    '/Pan\\/Select|Draw/',
    'Changes the active touch note-editing mode explicitly.',
    'repeated',
  ),
  mobile(
    'mobile.notes.edit-selected',
    'studio',
    'button',
    'Edit selected note',
    'Opens precise pitch, timing, velocity, and delete controls.',
  ),
  mobile(
    'mobile.sheet.keyboard',
    'studio',
    'dialog',
    '/.+/',
    'Traps focus inside the active sheet and closes it with Escape.',
    'one',
    'Custom full-screen sheet keyboard surface.',
  ),
  mobile(
    'mobile.sheet.close',
    'studio',
    'button',
    '/Close .+/',
    'Closes the active full-screen sheet and restores focus.',
  ),
  mobile(
    'mobile.note-field.decrease',
    'studio',
    'button',
    '/Decrease .+/',
    'Decreases a selected note value within its valid range.',
    'repeated',
  ),
  mobile(
    'mobile.note-field.value',
    'studio',
    'spinbutton',
    '/Pitch|Start|Duration|Velocity/',
    'Sets a precise selected-note value within its valid range.',
    'repeated',
  ),
  mobile(
    'mobile.note-field.increase',
    'studio',
    'button',
    '/Increase .+/',
    'Increases a selected note value within its valid range.',
    'repeated',
  ),
  mobile(
    'mobile.note.delete',
    'studio',
    'button',
    'Delete note',
    'Deletes the selected note and clears the mobile selection.',
  ),
  mobile(
    'mobile.coach.dismiss',
    'studio',
    'button',
    '/Dismiss .+/',
    'Dismisses contextual guidance without blocking the workspace.',
  ),
  traced('src/app/StudioNavigationGuard.test.tsx', 'e2e/routing.spec.ts')(
    'studio.autosave.retry',
    'studio',
    'button',
    'Retry save',
    'Retries a failed route-exit autosave and proceeds only after it succeeds.',
  ),
  traced('src/app/StudioNavigationGuard.test.tsx', 'e2e/routing.spec.ts')(
    'studio.autosave.discard',
    'studio',
    'button',
    '/Discard changes|Discarding changes\\.\\.\\./',
    'Explicitly abandons a failed route-exit autosave and continues navigation.',
  ),
  examplePlugin(
    'studio.plugins.example.run-command',
    'studio',
    'button',
    'Insert a C-major chord',
    'Runs the example plugin command and inserts its chord.',
  ),

  onboarding(
    'onboarding.launch',
    'onboarding',
    'button',
    'Take a tour',
    'Opens the onboarding dialog and moves focus to its primary action.',
  ),
  onboarding(
    'onboarding.dismiss-backdrop',
    'onboarding',
    'button',
    'Dismiss onboarding tour',
    'Closes onboarding and restores launcher focus.',
  ),
  onboarding(
    'onboarding.dialog.keyboard',
    'onboarding',
    'dialog',
    '/Welcome to Cadence|.+/',
    'Traps focus and handles Escape and arrow-key tour navigation.',
    'one',
    'Custom modal keyboard surface.',
  ),
  onboarding(
    'onboarding.close',
    'onboarding',
    'button',
    'Close onboarding tour',
    'Closes onboarding and restores launcher focus.',
  ),
  onboarding(
    'onboarding.step.select',
    'onboarding',
    'button',
    '/Go to step/',
    'Moves directly to the selected onboarding step and updates aria-current.',
    'repeated',
  ),
  onboarding(
    'onboarding.skip',
    'onboarding',
    'button',
    'Skip tour',
    'Marks onboarding complete and closes the dialog.',
  ),
  onboarding(
    'onboarding.back',
    'onboarding',
    'button',
    'Back',
    'Moves to the previous onboarding step.',
  ),
  onboarding(
    'onboarding.next',
    'onboarding',
    'button',
    '/Next|Get started/',
    'Moves to the next step or completes onboarding on the final step.',
  ),

  stems(
    'stems.close',
    'stems',
    'button',
    'Back to composer',
    'Returns from stems to the composer.',
  ),
  stems(
    'stems.retry',
    'stems',
    'button',
    'Retry',
    'Retries loading retained stem-separation jobs.',
  ),
  stems(
    'stems.upgrade',
    'stems',
    'button',
    'See Pro plans',
    'Opens pricing from the free-tier stems gate.',
  ),
  stems(
    'stems.upload.file',
    'stems',
    'button',
    'Choose a mix to separate',
    'Stores the selected native audio file and clears stale errors.',
    'one',
    'Native file input.',
  ),
  stems(
    'stems.separate',
    'stems',
    'button',
    '/Separate stems|Uploading/',
    'Uploads the mix and renders the resulting separation job or error.',
  ),
  stems(
    'stems.preview',
    'stems',
    'audio',
    '/.+ stem preview/',
    'Uses native media controls to play, pause, seek, or adjust a repeated stem preview.',
    'repeated',
    'Native media controls.',
  ),
  stems(
    'stems.download',
    'stems',
    'link',
    '/Download .+/',
    'Downloads the repeated generated stem as a named WAV file.',
    'repeated',
    'Native download link.',
  ),
]

export const interactionIds = new Set(interactionManifest.map(({ id }) => id))
